[project]
name = "image-reverse-search"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Nilay Dawn", email = "nilaydawn@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "faiss-cpu>=1.15.1",
    "fastapi>=0.142.2",
    "numpy>=2.4.6",
    "onnx>=1.23.1",
    "onnxruntime>=1.30.0",
    "pandas>=3.0.6",
    "pillow>=12.3.0",
    "psycopg2-binary>=2.9.13",
    "pydantic-settings>=2.15.0",
    "python-multipart>=0.0.32",
    "scikit-learn>=1.9.1",
    "supabase>=2.31.0",
    "tensorflow-cpu>=2.21.0",
    "tf2onnx>=1.17.0",
    "tqdm>=4.70.1",
    "uvicorn[standard]>=0.54.0",
]

